name: Secrets
run-name: Running Secrets.yml
on: [push]
jobs:
  DoThings:
    runs-on: ubuntu-latest
    steps:
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
